import locationsData from "@/data/locations.json";
import catalogData from "@/data/activity-catalog.json";
import aliasData from "@/data/activity-aliases.json";
import type { ActivityAlias, ActivityCatalogItem, Direction, Execution, Location } from "./types";
export const LOCATIONS=locationsData as Location[]; export const CATALOG=catalogData as ActivityCatalogItem[]; export const ALIASES=aliasData as ActivityAlias[];
const catalogById=new Map(CATALOG.map(x=>[x.id,x]));
export function normalizeText(value:unknown){return String(value??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[ªº]/g,"").replace(/[³²·]/g," ").replace(/\(\s*\*\s*\)/g,"").replace(/\s*\((?:m3|m2|m³|m²|m3\s*[x·]\s*km|m³\s*[x·]\s*km|kg|un|vb|dm3|dm³|m)\)\s*$/i,"").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
const aliasByNorm=new Map<string,string>(); for(const a of ALIASES) aliasByNorm.set(normalizeText(a.alias),a.activity_id); for(const x of CATALOG) aliasByNorm.set(normalizeText(x.name),x.id);
export function parseKm(input:unknown):number|null{if(input===null||input===undefined||input==="")return null;if(typeof input==="number"){if(!Number.isFinite(input))return null;if(input>=1000)return Math.round(input);const whole=Math.trunc(input);const dec=Math.abs(input-whole);return whole*1000+Math.round(dec*1000);}const raw=String(input).trim().replace(/\s/g,"");const p=raw.match(/^(\d{1,3})\+(\d{1,3})$/);if(p)return Number(p[1])*1000+Number(p[2].padStart(3,"0"));const s=raw.replace(",", ".");if(/^\d+(?:\.\d+)?$/.test(s)){const [a,b=""]=s.split(".");if(Number(a)>=1000&&!b)return Number(a);return Number(a)*1000+(b?Number(b.padEnd(3,"0").slice(0,3)):0);}return null;}
export function formatKm(m:number|null|undefined){if(m==null||!Number.isFinite(m))return"";const k=Math.floor(m/1000),mm=Math.round(m-k*1000);return `${String(k).padStart(3,"0")}+${String(mm).padStart(3,"0")}`;}
export function normalizeDirection(input:unknown):Direction{const s=normalizeText(input);if(s==="pn"||s==="n"||s.includes("norte"))return"PN";if(s==="ps"||s==="s"||s.includes("sul"))return"PS";return null;}
export function measurementForDate(iso:string){const d=new Date(`${iso}T12:00:00`);if(Number.isNaN(d.getTime()))return"";const day=d.getDate(),y=d.getFullYear(),m=d.getMonth()+1;const sm=day>=11?m:(m===1?12:m-1),sy=day>=11?y:(m===1?y-1:y);const med=5+((sy*12+sm)-(2026*12+8));return `MED ${String(med).padStart(2,"0")}`;}
export function mapActivity(raw:string){const id=aliasByNorm.get(normalizeText(raw));if(id){const x=catalogById.get(id);return{activity_id:id,activity_name:x?.name??raw,status:"MAPPED" as const};}return{activity_id:null,activity_name:null,status:"PENDING" as const,reason:"ATIVIDADE PENDENTE DE VINCULAÇÃO"};}
function explicitStructure(text:string){for(const l of LOCATIONS.filter(x=>x.type!=="FRENTE")){if(new RegExp(`\\b${l.code.replace("-","\\-")}\\b`,`i`).test(text))return l;if(l.km_anchor&&normalizeText(text).includes(normalizeText(formatKm(l.km_anchor))))return l;}return null;}
function explicitFront(text:string){const m=text.match(/FRENTE\s*[-:]?\s*([A-J])\b/i);return m?m[1].toUpperCase():null;}
function frontForKm(km:number){const fs=LOCATIONS.filter(x=>x.type==="FRENTE"&&x.km_start!=null&&x.km_end!=null);for(const f of fs)if(km>=f.km_start!&&km<f.km_end!)return f;const last=fs[fs.length-1];return last&&km===last.km_end?last:null;}
export function classifyLocation(ex:Execution):Execution{const a=parseKm(ex.km_start_raw),b=parseKm(ex.km_end_raw),min=a!=null&&b!=null?Math.min(a,b):(a??b),max=a!=null&&b!=null?Math.max(a,b):(a??b),orientation=a==null||b==null||a===b?"POINT":a<b?"ASC":"DESC";const evidence=[ex.ramo_local,ex.notes,ex.activity_raw].filter(Boolean).join(" | ");const structure=explicitStructure(evidence);const explicit=ex.front?.toUpperCase()||explicitFront(evidence);const calc=min!=null?frontForKm(min):null;let lt=ex.location_type??null,lc=ex.location_code??null,status:Execution["classification_status"]="OK";if(structure){lt=structure.type;lc=structure.code;}else if(explicit){lt="FRENTE";lc=explicit;if(calc&&calc.code!==explicit)status="CONFLICT";}else if(calc){lt="FRENTE";lc=calc.code;}else status=min!=null?"NO_FRONT":"REVIEW";return{...ex,km_start_m:a,km_end_m:b,km_min_m:min,km_max_m:max,original_orientation:orientation,front:lt==="FRENTE"?lc:ex.front??null,location_type:lt,location_code:lc,classification_status:status};}
export function normalizeExecution(ex:Execution):Execution{const m=mapActivity(ex.activity_raw);return classifyLocation({...ex,direction:normalizeDirection(ex.direction),measurement:ex.measurement||measurementForDate(ex.date),activity_id:ex.activity_id??m.activity_id,activity_name:ex.activity_name??m.activity_name,mapping_status:ex.activity_id?"MAPPED":m.status,mapping_reason:m.reason??null});}
